### ISSUE TITLE
building using MBAS fails

### ISSUE THREAD

**Issue by Selur** [ultravideo/kvazaar#225] opened 2019-04-16 17:47 UTC
using https://github.com/jb-alvarado/media-autobuild_suite build fails with:
```
19:34:52 ┌ kvazaar git .............................. [Recently updated]
19:34:52 ├ Running autogen...
19:35:29 ├ Running configure...
19:36:27 ├ Running make...
Likely error:
       __m128i a = _mm_cvtsi64_si128(*(int64_t *)(pic_data + y * pic_stride));
                   ^~~~~~~~~~~~~~~~~
../../src/strategies/sse41/reg_sad_pow2_widths-sse41.h:710:19: error: incompatible types when initializing type '__m128i {aka __vector(2) long long int}' using type 'int'
       __m128i b = _mm_cvtsi64_si128(*(int64_t *)(ref_data + y * ref_stride + leftoff));
                   ^~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1136: strategies/avx2/libavx2_la-picture-avx2.lo] Error 1
make[2]: Leaving directory '/build/kvazaar-git/build-32bit/src'
make[1]: *** [Makefile:524: all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-32bit'
make: *** [Makefile:394: all] Error 2
make failed. Check I:/media-autobuild_suite/build/kvazaar-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
```
Attached the log: [ab-suite.make.log](https://github.com/ultravideo/kvazaar/files/3086199/ab-suite.make.log)

**Comment by Arizer** [comment] 2019-04-16 18:59
Thanks once again for the report. We _really_ should add AppVeyor notifications since we have the tests running (and failing).

**Comment by moptim** [comment] 2019-05-23 16:58
The _mm_cvtsi64_si128 intrinsic seems in general to be troublesome on 32-bit builds. I had fixed an apparently-related problem on Win32 in https://github.com/ultravideo/kvazaar/commit/87a9208db8930b8f19cc808454023ec984b58a61, is this issue also fixed by it?

**Comment by Arizer** [comment] 2019-06-13 16:58
I built the 32-bit Kvazaar with a fresh clone of the suite and everything completed successfully. I guess the issue is resolved.

As a sidenote: AppVeyor notifications are now on the tasklist.

**Closed by Arizer** 2019-06-13 16:58 UTC

**Comment by Arizer** [comment] 2019-06-24 15:57
Email notifications for AppVeyor tests are now enabled.
