### ISSUE TITLE
Missing AVX2 instructions not correctly recognized

### ISSUE THREAD

**Issue by Dando-Real-ITA** [ultravideo/kvazaar#228] opened 2019-06-10 22:29 UTC
Hi,
on a processor ( Xeon E5-2690 ) which does not have any of the avx2/bmi instruction sets, this line still evaluates to true, then failing to compile, while if I edit it to force to false, I can compile successfully without avx2
I guess that the compiler allows the -mavx2 flag for cross-compiling, while if I use -march=native I get the -mno-avx2 flag

https://github.com/ultravideo/kvazaar/blob/3fe2f29456b0b8534cfc20ef0d1a52e2c8df26c4/configure.ac#L57

**Comment by Arizer** [comment] 2019-06-11 16:01
Hi,

What is the actual error you get when compiling?

AVX2 is used for optional optimizations only and compiling such code should not cause an issue. HAVE_AVX2 is set based on the detected compiler support for the instrcution sets. The compiler does not need support from CPU to generate for example AVX2 code.

Kvazaar executable itself should check the CPU flags for supported ISA extensions when started and use only the code the CPU is able to run even if code with unsupported instructions was present in the executable.

**Comment by Arizer** [comment] 2019-08-08 12:25
Closing the issue. Feel free to open this again if the issue persists.

**Closed by Arizer** 2019-08-08 12:25 UTC

**Comment by klondi** [comment] 2021-05-16 17:05
Hello, we have found what seems to be the same issue on Gentoo once we stabilized kvazaar 2.0.0 see https://bugs.gentoo.org/739776

The issue seems to be caused by the fact that in modern versions of gcc -mabm does not entail -mlzcnt. I provided a patch there that solves the issue, but I'm not sure it will be enough to merge in upstream.
